# Generated by Django 5.1.1 on 2024-09-10 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_delete_person'),
    ]

    operations = [
        migrations.CreateModel(
            name='Phonenumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.IntegerField(unique=True)),
            ],
        ),
    ]
