# Generated by Django 5.1.1 on 2024-09-11 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_person_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='contact',
            field=models.CharField(max_length=15),
        ),
    ]
