# Generated by Django 5.1.1 on 2024-09-11 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_person_candidatecode_alter_person_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='contact',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
